### ISSUE TITLE
Crash appears when enter wrong player class

### ISSUE THREAD

**Issue by orzAtalod** [ForgottenArbiter/SeedSearch#9]
When entered "THE_DEFECT" instead of "DEFECT" in the player class area, the searcher will crash with such message:

···
java.lang.NullPointerException
	at com.megacrit.cardcrawl.characters.CharacterManager.setChosenCharacter(CharacterManager.java:51)
	at seedsearch.SeedRunner.<init>(SeedRunner.java:73)
	at seedsearch.SeedSearch.search(SeedSearch.java:51)
	at seedsearch.patches.StartSearch.Insert(StartSearch.java:35)
	at com.megacrit.cardcrawl.core.CardCrawlGame.create(CardCrawlGame.java:299)
	at com.badlogic.gdx.backends.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:111)
	at com.badlogic.gdx.backends.headless.HeadlessApplication$1.run(HeadlessApplication.java:96)
···

**Comment by ForgottenArbiter** [comment]
Thanks for reporting this. In [637b1da](https://github.com/ForgottenArbiter/SeedSearch/commit/637b1da3ba3f9c5c48910671f5ec8f60c6c728d0) it should handle invalid player classes more gracefully and print a list of valid classes if the player makes a mistake when entering the player class.
